### PR TITLE
Bump core tracker version

### PR DESCRIPTION
**Pull request by gcoombe**
There have been many updates to the core tracker that I would like to take advantage on. Since the tracker is on 0.x.x a bump of the second digit is considered a major bump so currently this package only gets 0.5.x

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by gcoombe** [comment]
I signed!

**Comment by chuwy** [comment]
It seems @snowplowcla is on holidays... Confirmed @gcoombe signed our Software Grant and Corporate Contributor License Agreement v1.0.

**Comment by mmclead** [comment]
Is this going to be merged?

**Comment by paulboocock** [comment]
It will be merged yes. We have work planned for both this tracker and the JavaScript tracker in Q3 so it'll be released soon-ish. Sorry it's taken so long to get back around to this tracker.

**Comment by gcoombe** [comment]
@paulboocock is there anything blocking this release? Are you saying that merging this is dependent on additional tracker work?

**Comment by paulboocock** [comment]
No, there isn't anything blocking but we have a cycle where we will be working on specific trackers and the JavaScript based trackers are in Q3 (which we're in now so the wait shouldn't be too long). However, the reason I don't want to release just this PR is because we'll likely want to include one or two other things in the next release too that will needed testing together.

**Pull request merged**
