### PR TITLE
Update project dependencies and payload schema

### PR DESCRIPTION
**Pull request by clark-pan**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by clark-pan** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @clark-pan  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by clark-pan** [comment]
Any issues with this @mhadam @chuwy ? I've been using my fork of this for a few weeks and it seems to work fine.

**Comment by BenFradet** [comment]
hey @mhadam , could you have a look? Thanks.

**Review by paulboocock — APPROVED** [review]

**Pull request merged**
